const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    CHANGE_USER_VIEW: 'CHANGE_USER_VIEW',

    FETCH_ALL_USER_SUCCEED: 'FETCH_ALL_USER_SUCCEED',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',

    FETCH_ALL_ROLE_SUCCEED: 'FETCH_ALL_ROLE_SUCCEED',
    FETCH_ALL_ROLE_FAILED: 'FETCH_ALL_ROLE_FAILED',

    FETCH_ALL_TYPE_SUCCEED: 'FETCH_ALL_TYPE_SUCCEED',
    FETCH_ALL_TYPE_FAILED: 'FETCH_ALL_TYPE_FAILED',

    FETCH_ALL_POS_SUCCEED: 'FETCH_ALL_POS_SUCCEED',
    FETCH_ALL_POS_FAILED: 'FETCH_ALL_POS_FAILED',

    DELETE_USER_SUCCEED: 'DELETE_USER_SUCCEED',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    
    ADD_USER_SUCCEED: 'ADD_USER_SUCCEED',
    ADD_USER_FAILED: 'ADD_USER_FAILED',

    GET_A_USER_SUCCEED: 'GET_A_USER_SUCCEED',
    GET_A_USER_FAILED: 'GET_A_USER_FAILED',

    EDIT_USER_ID: 'EDIT_USER_ID',

    UPDATE_USER_SUCCEED: 'UPDATE_USER_SUCCEED',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    UPDATE_ADD_USER_LOADING : 'UPDATE_ADD_USER_LOADING',
    UPDATE_EDIT_USER_LOADING: 'UPDATE_EDIT_USER_LOADING',
    UPDATE_DELETE_USER_LOADING : 'UPDATE_DELETE_USER_LOADING',

    GET_IMAGE_LINK_SUCCEED: 'GET_IMAGE_LINK_SUCCEED',
    GET_IMAGE_LINK_FAILED: 'GET_IMAGE_LINK_FAILED',
})

export default actionTypes;